restores buildx

diff --git a/build-bin/docker/configure_docker_push b/build-bin/docker/configure_docker_push
--- a/build-bin/docker/configure_docker_push
+++ b/build-bin/docker/configure_docker_push
@@ -13,7 +13,7 @@
 # the License.
 #
 
-# Ensures Docker is logged in and it can build multi-architecture.
+# Ensures Docker is logged in, buildx is available and it can build multi-architecture.
 # This should be used instead of `configure_docker` when a push will occur.
 #
 # This should only happen when we are publishing multi-arch builds, as otherwise the setup could use
@@ -32,7 +32,7 @@ fi
 echo '{ "experimental":true, "registry-mirrors": ["https://mirror.gcr.io"] }' | sudo tee /etc/docker/daemon.json
 
 sudo service docker restart
-# Enable experimental client features (multi-arch)
+# Enable experimental client features (eg docker buildx)
 mkdir -p ${HOME}/.docker && echo '{"experimental":"enabled"}' > ${HOME}/.docker/config.json
 
 # Log in to GitHub Container Registry and Docker Hub for releasing images
@@ -46,9 +46,21 @@ if [ -n "${DOCKERHUB_USER:-}" ]; then
   echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USER}" --password-stdin
 fi
 
+# Connection resets are frequent in GitHub Actions workflows
+alias wget="wget --random-wait --tries=5 -qO-"
+
+# Latest version from https://github.com/docker/buildx/releases
+buildx_version=0.5.1
+buildx_url=https://github.com/docker/buildx/releases/download/v${buildx_version}/buildx-v${buildx_version}.linux-${arch}
+mkdir -p $HOME/.docker/cli-plugins
+( cd $HOME/.docker/cli-plugins && wget ${buildx_url} > docker-buildx && chmod 755 docker-buildx)
+docker version
+
 # Enable execution of different multi-architecture containers by QEMU and binfmt_misc
 # See https://github.com/multiarch/qemu-user-static
 #
 # Mirrored image use to avoid docker.io pulls:
 # docker tag multiarch/qemu-user-static:5.1.0-7 ghcr.io/openzipkin/multiarch-qemu-user-static:latest
 docker run --rm --privileged ghcr.io/openzipkin/multiarch-qemu-user-static --reset -p yes
+# don't fail if there's already a builder
+docker buildx create --name builder --use || true
